### ISSUE TITLE
Send SMS form to order detail

### ISSUE THREAD

**Issue by lukaspijak** [BulkGate/woosms#1]

**Comment by robert1112** [comment]
@lukaspijak 
It will be better and more convenient to be able to use 'template'  from the drop down feature. Thanks.

**Comment by robert1112** [comment]
Thank you
On Sep 26, 2018, 8:20 PM +0800, Lukáš Piják <notifications@github.com>, wrote:

Prepared for new version

**Comment by lukaspijak** [comment]
Added to version 2.0.14. You can download it from WordPress plugins.

**Comment by lukaspijak** [comment]
![image](https://user-images.githubusercontent.com/2571714/46081546-0b651400-c19d-11e8-9d0c-2b5c33689f0a.png)
