### ISSUE TITLE
Wordpress Multisite Issue

### ISSUE THREAD

**Issue by GEE911** [BulkGate/woosms#3]
I am using WOOSMS on a WP Multisite. I have installed the plugin on the main site where it works fine (c2o.co.za). However, when I try to login to the dashboard from any of the multi sites (site1.c2o.co.za), I login with my username and password into the dashboard and it tells me 'sorry, you are not allowed to access this page'. I contacted support, and they fixed it on one of my multi sites, which is working, but I need to know how to fix it myself so that whenever I add new multi sites, the plugin works.

**Comment by GEE911** [comment]
![image](https://user-images.githubusercontent.com/25619514/82656009-4f831300-9c23-11ea-890d-f20666160014.png)


This was the response I got from support, but I wasn't shown how to actually fix the issue.

**Comment by lukaspijak** [comment]
Hello,

you must create `XXX_bulkgate_module` table, becouse WP Multisite using multiple prefixed tables names and if you create new site WooSMS dont native support the table creation for new site. We to try add support in next versions. But if you create the table manualy WooSMS will be work ok.

```sql
            CREATE TABLE IF NOT EXISTS `PREFIX_bulkgate_module` (
              `scope` varchar(50) NOT NULL DEFAULT 'main',
              `key` varchar(50) NOT NULL,
              `type` enum('text','int','float','bool','json') DEFAULT 'text',
              `value` text NOT NULL,
              `datetime` bigint(20) DEFAULT NULL,
              `order` int(11) NOT NULL DEFAULT '0',
              `synchronize_flag` enum('none','add','change','delete') NOT NULL DEFAULT 'none',
              PRIMARY KEY (`scope`,`key`)
            ) DEFAULT CHARSET=utf8;
```

**Comment by GEE911** [comment]
Hi thanks. please advise how and where I actually create this table? Thanks

**Comment by lukaspijak** [comment]
Hi, do you have phpmyadmin or something like this?

**Comment by GEE911** [comment]
Unfortunately not

**Comment by GEE911** [comment]
Is there a way to insert these table without PHPMyAdmin?

**Comment by lukaspijak** [comment]
Ok, can you send FTP access to our support team?

https://www.bulkgate.com/en/contact-us/

We create the tables for you, if you want.
