### ISSUE TITLE
Send SMS just parent order | Dokan

### ISSUE THREAD

**Issue by AlexWebpuro** [BulkGate/woosms#4]
in our Wocommerce site, use Dokan, this generate parents order and sub order, we need to send SMS when Order is parent, i try to make this change in woosms_hook_changeOrderStatusHook() functiom, but I have not succeeded, is there any way to filter this to be able to send only when it is a parent order

Thanks

Best regards
![Screen-Shot-2021-09-21-at-7 47 18-PM](https://user-images.githubusercontent.com/17629020/134266338-55490c6a-90f3-44bb-8bbf-00e21d4cc5d1.jpg)

**Comment by lukaspijak** [comment]
Hi, 

maybe this filter could help you. 

https://github.com/BulkGate/woosms/blob/master/woosms-sms-module-for-woocommerce.php#L100

**Comment by AlexWebpuro** [comment]
Thanks, works for me!
